name: Ningin Deployment SSM and S3
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code(소스코드 가져오기)
        uses: actions/checkout@v4

      - name: Configure AWS credentials(AWS 자격 증명 구성)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync html/ s3://${{ secrets.S3_BUCKET_NAME }}/html/ --delete

      - name: Deploy from S3 to EC2 using SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RUnShellSCript" \ # 마음대로 지정 가능
            --parameters "commands=[
                \"sudo aws s3 sync s3://${{ secrets.S3_BUCKET_NAME }}/html/ /usr/share/nginx/html/ --delete\"
                \"sudo chown -R ec2-user:nginx /usr/share/nginx/html/\"
                \"sudo systemctl reload nginx\"
            ]" \
            --region ${{ secrets.AWS_REGION }}
            --comment "Deploying website from S3 to EC2 using SSM"